# Generated by Django 3.2.25 on 2024-08-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_good_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_open_for_all',
            field=models.BooleanField(default=False, verbose_name='Открыт для всех'),
        ),
    ]
